<template>
  <client-only>
    <vue-plotly :data="violinData" :layout="layout" :display-mode-bar="false" />
  </client-only>
</template>

<script>
// Utilities

export default {
  name: 'DatasetViolinplot',
  props: {
    result: {
      type: Object,
      required: true,
      default: () => ({
        x: [
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Oligodendrocyte precursor cells',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia',
          'Microglia'
        ],
        y: [
          10.34,
          21.01,
          23.68,
          24.59,
          25.29,
          8.77,
          26.88,
          15.04,
          14.78,
          10.27,
          35.26,
          15.42,
          18.43,
          14.83,
          21.58,
          10.33,
          16.29,
          16.97,
          20.65,
          17.92,
          20.29,
          15.77,
          39.42,
          19.82,
          17.81,
          13.37,
          12.69,
          21.7,
          19.65,
          9.55,
          18.35,
          15.06,
          20.69,
          17.78,
          24.06,
          16.31,
          16.93,
          18.69,
          31.27,
          16.04,
          17.46,
          13.94,
          9.68,
          30.4,
          18.29,
          22.23,
          32.4,
          28.55,
          18.04,
          12.54,
          10.29,
          34.81,
          9.94,
          25.56,
          19.49,
          38.01,
          26.41,
          11.24,
          48.27,
          20.29,
          17.92,
          27.2,
          22.76,
          17.29,
          19.44,
          16.66,
          10.07,
          32.68,
          15.98,
          34.83,
          13.03,
          18.28,
          24.71,
          21.16,
          28.97,
          22.49,
          5.75,
          16.32,
          22.75,
          40.17,
          27.28,
          12.03,
          21.01,
          12.46,
          11.35,
          15.38,
          44.3,
          22.42,
          20.92,
          15.36,
          20.49,
          25.21,
          18.24,
          14.31,
          14,
          7.25,
          38.07,
          23.95,
          25.71,
          17.31,
          29.93,
          10.65,
          12.43,
          24.08,
          11.69,
          13.42,
          14.26,
          15.95,
          12.48,
          29.8,
          8.52,
          14.52,
          11.38,
          22.82,
          19.08,
          20.27,
          11.17,
          12.26,
          18.26,
          8.51,
          10.33,
          14.15,
          16,
          13.16,
          17.47,
          34.3,
          41.19,
          27.05,
          16.43,
          8.35,
          18.64,
          11.87,
          9.78,
          7.51,
          14.07,
          13.13,
          17.26,
          24.55,
          19.77,
          29.85,
          48.17,
          25,
          13.39,
          16.49,
          21.5,
          12.66,
          16.21,
          13.81,
          17.51,
          24.52,
          20.76,
          31.71,
          10.59,
          10.63,
          50.81,
          15.81,
          7.25,
          31.85,
          16.82,
          32.9,
          17.89,
          14.48,
          16.47
        ]
      })
    }
  },
  data: () => ({ fab: false }),

  computed: {
    violinData() {
      return [
        {
          type: 'violin',
          x: this.result.names,
          y: this.result.expression,
          legendgroup: 'F',
          scalegroup: 'F',
          name: this.result.geneName,
          box: {
            visible: true
          },
          line: {
            color: 'pink'
          },
          meanline: {
            visible: true
          }
        }
      ]
    },
    layout() {
      return {
        title: {
          text: this.result.geneName + ' : ' + this.result.clusterName,
          font: {
            size: 20
          }
        },
        autosize: true,
        yaxis: {
          zeroline: false
        },
        violinmode: 'group'
      }
    }
  },
  methods: {
    onScroll() {}
  }
}
</script>
