<template>
  <div>
    <v-layout column justify-center align-center>
      <p class="display-3 font-weight-regular" align-center>
        scREAD (dev) NewGraph
      </p>
      <v-flex xs="12" md="6" lg="12">
        <p class="display-1">
          NewGraph Test
        </p>
      </v-flex>
    </v-layout>

    <client-only>
      <vue-plotly
        :data="pieData1"
        :layout="layout1"
        :options="options"
        :display-mode-bar="false"
      />
      <vue-plotly
        :data="barData1"
        :layout="layout2"
        :display-mode-bar="false"
      />
      <vue-plotly
        :data="barData2"
        :layout="layout3"
        :display-mode-bar="false"
      />
      <vue-plotly
        :data="violinData"
        :layout="layout4"
        :display-mode-bar="false"
      />
      <vue-plotly :data="dotData" :layout="layout5" :display-mode-bar="false" />
    </client-only>
  </div>
</template>

<script>
export default {
  data() {
    return {
      pieData1: [
        {
          values: [1874, 3692, 4145, 4281, 7370, 2412, 1162],
          labels: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          type: 'pie'
        }
      ],
      layout1: {
        title: {
          text: 'Species',
          font: {
            size: 20
          }
        },
        autosize: true,
        width: this.pieWidth,
        height: 500,
        margin: {
          l: 20,
          r: 20,
          b: 210,
          t: 50,
          pad: 4
        },
        legend: {
          font: {
            size: 14
          },
          orientation: 'h'
        }
      },
      barData1: [
        {
          x: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          y: [1874, 3692, 4145, 4281, 7370, 2412, 1162],
          name: 'dataset1',
          type: 'bar'
        },
        {
          x: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          y: [2274, 3692, 5045, 2281, 9370, 7112, 562],
          name: 'dataset2',
          type: 'bar'
        }
      ],
      layout2: {
        title: {
          text: 'Number of Cells',
          font: {
            size: 20
          }
        },
        autosize: true,
        barmode: 'stack'
      },
      barData2: [
        {
          x: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          y: [41, 24, 52, 78, 71, 36, 52],
          name: 'dataset1',
          type: 'bar'
        },
        {
          x: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          y: [59, 76, 48, 22, 29, 64, 48],
          name: 'dataset2',
          type: 'bar'
        }
      ],
      layout3: {
        title: {
          text: 'Percentage of cells',
          font: {
            size: 20
          }
        },
        autosize: true,
        barmode: 'stack'
      },
      violinData: [
        {
          type: 'violin',
          x: [
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Astrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons'
          ],
          y: [
            16.99,
            10.34,
            21.01,
            23.68,
            24.59,
            25.29,
            8.77,
            26.88,
            15.04,
            14.78,
            10.27,
            35.26,
            15.42,
            18.43,
            14.83,
            21.58,
            10.33,
            16.29,
            16.97,
            20.65,
            17.92,
            20.29,
            15.77,
            39.42,
            19.82,
            17.81,
            13.37,
            12.69,
            21.7,
            19.65,
            9.55,
            18.35,
            15.06,
            20.69,
            17.78,
            24.06,
            16.31,
            16.93,
            18.69,
            31.27,
            16.04,
            17.46,
            13.94,
            9.68,
            30.4,
            18.29,
            22.23,
            32.4,
            28.55,
            18.04,
            12.54,
            10.29,
            34.81,
            9.94,
            25.56,
            19.49,
            38.01,
            26.41,
            11.24,
            48.27,
            20.29,
            13.81,
            11.02,
            18.29,
            17.59,
            20.08,
            16.45,
            3.07,
            20.23,
            15.01,
            12.02,
            17.07,
            26.86,
            25.28,
            14.73,
            10.51,
            17.92,
            27.2,
            22.76,
            17.29,
            19.44,
            16.66,
            10.07,
            32.68,
            15.98,
            34.83,
            13.03,
            18.28,
            24.71,
            21.16,
            28.97,
            22.49,
            5.75,
            16.32,
            22.75,
            40.17,
            27.28,
            12.03,
            21.01,
            12.46,
            11.35,
            15.38,
            44.3,
            22.42,
            20.92,
            15.36,
            20.49,
            25.21,
            18.24,
            14.31,
            14,
            7.25,
            38.07,
            23.95,
            25.71,
            17.31,
            29.93,
            10.65,
            12.43,
            24.08,
            11.69,
            13.42,
            14.26,
            15.95,
            12.48,
            29.8,
            8.52,
            14.52,
            11.38,
            22.82,
            19.08,
            20.27,
            11.17,
            12.26,
            18.26,
            8.51,
            10.33,
            14.15,
            16,
            13.16,
            17.47,
            34.3,
            41.19,
            27.05,
            16.43,
            8.35,
            18.64,
            11.87,
            9.78,
            7.51,
            14.07,
            13.13,
            17.26,
            24.55,
            19.77,
            29.85,
            48.17,
            25,
            13.39,
            16.49,
            21.5,
            12.66,
            16.21,
            13.81,
            17.51,
            24.52,
            20.76,
            31.71,
            10.59,
            10.63,
            50.81,
            15.81,
            7.25,
            31.85,
            16.82,
            32.9,
            17.89,
            14.48,
            9.6,
            34.63,
            34.65,
            23.33,
            45.35,
            23.17,
            40.55,
            20.69,
            20.9,
            30.46,
            18.15,
            23.1,
            15.69,
            19.81,
            28.44,
            15.48,
            16.58,
            7.56,
            10.34,
            43.11,
            13,
            13.51,
            18.71,
            12.74,
            13,
            16.4,
            20.53,
            16.47,
            26.59,
            38.73,
            24.27,
            12.76,
            30.06,
            25.89,
            48.33,
            13.27,
            28.17,
            12.9,
            28.15,
            11.59,
            7.74,
            30.14,
            12.16,
            13.42,
            8.58,
            15.98,
            13.42,
            16.27,
            10.09,
            20.45,
            13.28,
            22.12,
            24.01,
            15.69,
            11.61,
            10.77,
            15.53,
            10.07,
            12.6,
            32.83,
            35.83,
            29.03,
            27.18,
            22.67,
            17.82,
            18.78,
            16.99,
            10.34,
            21.01,
            23.68,
            24.59,
            25.29,
            8.77,
            26.88,
            15.04,
            14.78,
            10.27,
            35.26,
            15.42,
            18.43,
            14.83,
            21.58,
            10.33,
            16.29,
            16.97,
            20.65,
            17.92,
            20.29,
            15.77,
            39.42,
            19.82,
            17.81,
            13.37,
            12.69,
            21.7,
            19.65,
            9.55,
            18.35,
            15.06,
            20.69,
            17.78,
            24.06,
            16.31,
            16.93,
            18.69,
            31.27,
            16.04,
            17.46,
            13.94,
            9.68,
            30.4,
            18.29,
            22.23,
            32.4,
            28.55,
            18.04,
            12.54,
            10.29,
            34.81,
            9.94,
            25.56,
            19.49,
            38.01,
            26.41,
            11.24,
            48.27,
            20.29,
            13.81,
            11.02,
            18.29,
            17.59,
            20.08,
            16.45,
            3.07,
            20.23,
            15.01,
            12.02,
            17.07,
            26.86,
            25.28,
            14.73,
            10.51,
            17.92,
            27.2,
            22.76,
            17.29,
            19.44,
            16.66,
            10.07,
            32.68,
            15.98,
            34.83,
            13.03,
            18.28,
            24.71,
            21.16,
            28.97,
            22.49,
            5.75,
            16.32,
            22.75,
            40.17,
            27.28,
            12.03,
            21.01,
            12.46,
            11.35,
            15.38,
            44.3,
            22.42,
            20.92,
            15.36,
            20.49,
            25.21,
            18.24,
            14.31,
            14,
            7.25,
            38.07,
            23.95,
            25.71,
            17.31,
            29.93,
            10.65,
            12.43,
            24.08,
            11.69,
            13.42,
            14.26,
            15.95,
            12.48,
            29.8,
            8.52,
            14.52,
            11.38,
            22.82,
            19.08,
            20.27,
            11.17,
            12.26,
            18.26,
            8.51,
            10.33,
            14.15,
            16,
            13.16,
            17.47,
            34.3,
            41.19,
            27.05,
            16.43,
            8.35,
            18.64,
            11.87,
            9.78,
            7.51,
            14.07,
            13.13,
            17.26,
            24.55,
            19.77,
            29.85,
            48.17,
            25,
            13.39,
            16.49,
            21.5,
            12.66,
            16.21,
            13.81,
            17.51,
            24.52,
            20.76,
            31.71,
            10.59,
            10.63,
            50.81,
            15.81,
            7.25,
            31.85,
            16.82,
            32.9,
            17.89,
            14.48,
            9.6,
            34.63,
            34.65,
            23.33,
            45.35,
            23.17,
            40.55,
            20.69,
            20.9,
            30.46,
            18.15,
            23.1,
            15.69,
            19.81,
            28.44,
            15.48,
            16.58,
            7.56,
            10.34,
            43.11,
            13,
            13.51,
            18.71,
            12.74,
            13,
            16.4,
            20.53,
            16.47
          ],
          legendgroup: 'M',
          scalegroup: 'M',
          name: 'dataset1',
          box: {
            visible: true
          },
          line: {
            color: 'blue'
          },
          meanline: {
            visible: true
          }
        },
        {
          type: 'violin',
          x: [
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Oligodendrocyte precursor cells',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Astrocytes',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Endothelial cells',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Microglia',
            'Astrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Inhibitory neurons',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Oligodendrocytes',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons',
            'Excitatory neurons'
          ],
          y: [
            16.99,
            10.34,
            21.01,
            23.68,
            24.59,
            25.29,
            8.77,
            26.88,
            15.04,
            14.78,
            10.27,
            35.26,
            15.42,
            18.43,
            14.83,
            21.58,
            10.33,
            16.29,
            16.97,
            20.65,
            17.92,
            20.29,
            15.77,
            39.42,
            19.82,
            17.81,
            13.37,
            12.69,
            21.7,
            19.65,
            9.55,
            18.35,
            15.06,
            20.69,
            17.78,
            24.06,
            16.31,
            16.93,
            18.69,
            31.27,
            16.04,
            17.46,
            13.94,
            9.68,
            30.4,
            18.29,
            22.23,
            32.4,
            28.55,
            18.04,
            12.54,
            10.29,
            34.81,
            9.94,
            25.56,
            19.49,
            38.01,
            26.41,
            11.24,
            48.27,
            20.29,
            13.81,
            11.02,
            18.29,
            17.59,
            20.08,
            16.45,
            3.07,
            20.23,
            15.01,
            12.02,
            17.07,
            26.86,
            25.28,
            14.73,
            10.51,
            17.92,
            27.2,
            22.76,
            17.29,
            19.44,
            16.66,
            10.07,
            32.68,
            15.98,
            34.83,
            13.03,
            18.28,
            24.71,
            21.16,
            28.97,
            22.49,
            5.75,
            16.32,
            22.75,
            40.17,
            27.28,
            12.03,
            21.01,
            12.46,
            11.35,
            15.38,
            44.3,
            22.42,
            20.92,
            15.36,
            20.49,
            25.21,
            18.24,
            14.31,
            14,
            7.25,
            38.07,
            23.95,
            25.71,
            17.31,
            29.93,
            10.65,
            12.43,
            24.08,
            11.69,
            13.42,
            14.26,
            15.95,
            12.48,
            29.8,
            8.52,
            14.52,
            11.38,
            22.82,
            19.08,
            20.27,
            11.17,
            12.26,
            18.26,
            8.51,
            10.33,
            14.15,
            16,
            13.16,
            17.47,
            34.3,
            41.19,
            27.05,
            16.43,
            8.35,
            18.64,
            11.87,
            9.78,
            7.51,
            14.07,
            13.13,
            17.26,
            24.55,
            19.77,
            29.85,
            48.17,
            25,
            13.39,
            16.49,
            21.5,
            12.66,
            16.21,
            13.81,
            17.51,
            24.52,
            20.76,
            31.71,
            10.59,
            10.63,
            50.81,
            15.81,
            7.25,
            31.85,
            16.82,
            32.9,
            17.89,
            14.48,
            9.6,
            34.63,
            34.65,
            23.33,
            45.35,
            23.17,
            40.55,
            20.69,
            20.9,
            30.46,
            18.15,
            23.1,
            15.69,
            19.81,
            28.44,
            15.48,
            16.58,
            7.56,
            10.34,
            43.11,
            13,
            13.51,
            18.71,
            12.74,
            13,
            16.4,
            20.53,
            16.47,
            26.59,
            38.73,
            24.27,
            12.76,
            30.06,
            25.89,
            48.33,
            13.27,
            28.17,
            12.9,
            28.15,
            11.59,
            7.74,
            30.14,
            12.16,
            13.42,
            8.58,
            15.98,
            13.42,
            16.27,
            10.09,
            20.45,
            13.28,
            22.12,
            24.01,
            15.69,
            11.61,
            10.77,
            15.53,
            10.07,
            12.6,
            32.83,
            35.83,
            29.03,
            27.18,
            22.67,
            17.82,
            18.78,
            16.99,
            10.34,
            21.01,
            23.68,
            24.59,
            25.29,
            8.77,
            26.88,
            15.04,
            14.78,
            10.27,
            35.26,
            15.42,
            18.43,
            14.83,
            21.58,
            10.33,
            16.29,
            16.97,
            20.65,
            17.92,
            20.29,
            15.77,
            39.42,
            19.82,
            17.81,
            13.37,
            12.69,
            21.7,
            19.65,
            9.55,
            18.35,
            15.06,
            20.69,
            17.78,
            24.06,
            16.31,
            16.93,
            18.69,
            31.27,
            16.04,
            17.46,
            13.94,
            9.68,
            30.4,
            18.29,
            22.23,
            32.4,
            28.55,
            18.04,
            12.54,
            10.29,
            34.81,
            9.94,
            25.56,
            19.49,
            38.01,
            26.41,
            11.24,
            48.27,
            20.29,
            13.81,
            11.02,
            18.29,
            17.59,
            20.08,
            16.45,
            3.07,
            20.23,
            15.01,
            12.02,
            17.07,
            26.86,
            25.28,
            14.73,
            10.51,
            17.92,
            27.2,
            22.76,
            17.29,
            19.44,
            16.66,
            10.07,
            32.68,
            15.98,
            34.83,
            13.03,
            18.28,
            24.71,
            21.16,
            28.97,
            22.49,
            5.75,
            16.32,
            22.75,
            40.17,
            27.28,
            12.03,
            21.01,
            12.46,
            11.35,
            15.38,
            44.3,
            22.42,
            20.92,
            15.36,
            20.49,
            25.21,
            18.24,
            14.31,
            14,
            7.25,
            38.07,
            23.95,
            25.71,
            17.31,
            29.93,
            10.65,
            12.43,
            24.08,
            11.69,
            13.42,
            14.26,
            15.95,
            12.48,
            29.8,
            8.52,
            14.52,
            11.38,
            22.82,
            19.08,
            20.27,
            11.17,
            12.26,
            18.26,
            8.51,
            10.33,
            14.15,
            16,
            13.16,
            17.47,
            34.3,
            41.19,
            27.05,
            16.43,
            8.35,
            18.64,
            11.87,
            9.78,
            7.51,
            14.07,
            13.13,
            17.26,
            24.55,
            19.77,
            29.85,
            48.17,
            25,
            13.39,
            16.49,
            21.5,
            12.66,
            16.21,
            13.81,
            17.51,
            24.52,
            20.76,
            31.71,
            10.59,
            10.63,
            50.81,
            15.81,
            7.25,
            31.85,
            16.82,
            32.9,
            17.89,
            14.48,
            9.6,
            34.63,
            34.65,
            23.33,
            45.35,
            23.17,
            40.55,
            20.69,
            20.9,
            30.46,
            18.15,
            23.1,
            15.69,
            19.81,
            28.44,
            15.48,
            16.58,
            7.56,
            10.34,
            43.11,
            13,
            13.51,
            18.71,
            12.74,
            13,
            16.4,
            20.53,
            16.47
          ],
          legendgroup: 'F',
          scalegroup: 'F',
          name: 'dataset2',
          box: {
            visible: true
          },
          line: {
            color: 'pink'
          },
          meanline: {
            visible: true
          }
        }
      ],
      layout4: {
        title: {
          text: 'Number of Cells',
          font: {
            size: 20
          }
        },
        autosize: true,
        yaxis: {
          zeroline: false
        },
        violinmode: 'group'
      },
      dotData: [
        {
          x: [-1, 1.5, 0.3, 2, -1.8, -0.1, 1.8],
          y: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          name: 'AD00106 vs AD00101',
          mode: 'markers',
          marker: {
            color: 'rgba(156, 165, 196, 0.95)',
            line: {
              color: 'rgba(156, 165, 196, 1.0)',
              width: 1
            },
            symbol: 'circle',
            size: 16
          }
        },
        {
          x: [-2, 1.1, 1.9, 0.5, -0.8, -1.1, 0.8],
          y: [
            'Oligodendrocyte precursor cells',
            'Microglia',
            'Endothelial cells',
            'Astrocytes',
            'Oligodendrocytes',
            'Inhibitory neurons',
            'Excitatory neurons'
          ],
          name: 'AD00107 vs AD00101',
          mode: 'markers',
          marker: {
            color: 'rgba(204, 204, 204, 0.95)',
            line: {
              color: 'rgba(217, 217, 217, 1.0)',
              width: 1
            },
            symbol: 'circle',
            size: 16
          }
        }
      ],
      layout5: {
        title: {
          text: 'GAD1 gene logFC',
          font: {
            size: 20
          }
        },
        xaxis: {
          showgrid: false,
          showline: true,
          linecolor: 'rgb(102, 102, 102)',
          titlefont: {
            font: {
              color: 'rgb(204, 204, 204)'
            }
          },
          tickfont: {
            font: {
              color: 'rgb(102, 102, 102)'
            }
          },
          autotick: false,
          dtick: 10,
          ticks: 'outside',
          tickcolor: 'rgb(102, 102, 102)'
        },
        margin: {
          l: 140,
          r: 40,
          b: 50,
          t: 80
        },
        legend: {
          font: {
            size: 10
          },
          yanchor: 'middle',
          xanchor: 'right'
        },
        // width: 600,
        // height: 600,
        // paper_bgcolor: 'rgb(254, 247, 234)',
        // plot_bgcolor: 'rgb(254, 247, 234)',
        hovermode: 'closest'
      }
    }
  }
}
</script>
